---
- hosts: localhost
  connection: local
  pre_tasks:
    - name: Verify ansible version
      assert:
        that: "ansible_version.full is version_compare('2.7', '>=')"
        msg:
          "You must update Ansible to at least 2.7 to use this playbook"
    - pip:
        name: f5-sdk
  roles:
    - ../bigip
