---
- name: yum | {{ item }}
  tags: nrpe
  yum:
    name={{ item }}
    state=present
  register: nrpe_yum
  with_items: [ 'nrpe', 'nagios-plugins-all' ]

- name: template | nrpe.conf
  tags: nrpe
  template:
    src=nrpe.cfg.j2
    dest=/etc/nagios/nrpe.cfg
    owner=root
    group=root
    mode=0644
  when: nrpe_yum|success
  notify:
    - service | nrpe | restarted

- name: service | nrpe
  tags: nrpe
  service:
    name=nrpe
    enabled=yes
    state=started
  when: nrpe_yum|success

