---
- name: add node
  bigip_node:
    name: ctwasd01
    #ip: 10.1.2.151
    fqdn: ctwasd01.surveysampling.com 
    partition: Common
    provider:
      server: "{{ f5.tru.qa.primary }}"
      user: "{{ user }}"
      password: "{{ password }}"
      validate_certs: no
#  with_items:
#    - "{{ server_list }}"

- name: save config
  bigip_config:
    save: yes
    verify: no
    provider:
      server: "{{ f5.tru.qa.primary }}"
      user: "{{ user }}"
      password: "{{ password }}"
      validate_certs: no   

# - debug:
#    msg: "This is my var: {{ server_list }}"

# - name: "add node {{ item }}"
#   bigip_node:
#     address: "{{ item }}"
#     name: "{{ item }}"
#     fqdn_auto_populate: yes
#     fqdn_up_interval: 3600
#     monitors:
#       - icmp
#     fqdn_address_type: ipv4
#     fqdn: "{{ item }}"
#     state: "{{ server_state }}"
#     provider:
#       user: admin
#       password: c0wboys-Fa1l
#       server: "{{ f5.primary }}"
#       server_port: "{{ bigip_server_port }}"
#       transport: cli
#     fqdn_down_interval: 5
#   with_items:
#     - "{{ server_list }}"
