---
- name: yum | libselinux-python
  tags: selinux
  yum:
    name=libselinux-python
    state=present
  register: libselinux_python_yum

- name: command | sestatus
  tags: selinux
  command: >
    sestatus
  register: sestatus_result
  when: libselinux_python_yum.rc == 0

- name: command | setenforce
  tags: selinux
  command: >
    setenforce 0
  when:
    selinux_enable == False and
    sestatus_result.stdout.find('enabled') != -1
    
- name: selinux | disabled
  tags: selinux
  selinux:
    state=disabled
  when: 
    selinux_enable == False and
    libselinux_python_yum.rc == 0

- name: selinux | sysconfig
  tags: selinux
  template:
    src=selinux.sysconfig.j2
    dest=/etc/selinux/config
    owner=root
    group=root
    mode=0644
  when: libselinux_python_yum.rc == 0

